name: gio_frontend
version: 1.0.0+1
description: Proyecto Flutter para GIO
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http: ^1.5.0
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  characters: ^1.4.0

  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.1
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fondoprincipal.png
    - assets/este.quiero.png
    - assets/icono.png
